# configure extensions of otel collector
# - health_check: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
# - pprof: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/pprofextension
# - zpages: https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/zpagesextension
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

# configure receivers
# for more receiver values see:
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver

# configure how the collector receive data
# receive data over otlp protocol based on http or grpc
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

# batching or filtering
# documentation of default processors: https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor
# community processors: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor
processors:
  batch:

# configure exporters, which forward data to observability backends
# - Loki: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md
# - Prometheus: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
# - Jaeger: https://opentelemetry.io/blog/2023/jaeger-exporter-collector-migration/
exporters:
  debug:
    verbosity: detailed

  otlphttp/logs:
    endpoint: "${LOKI_ENDPOINT}"
    tls:
      insecure: true

  prometheus:
    endpoint: ":8889"

  otlp/jaeger:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true

# configure extensions to collector and pipelines for metrics, traces and logs
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
