# configure extensions of otel collector
# - health_check: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
# - pprof: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/pprofextension
# - zpages: https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/zpagesextension
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

# configure receivers
# for more receiver values see:
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver

# configure how the collector receive data
# receive data over otlp protocol based on http or grpc
receivers:
  otlp:
    protocols:
      http:
      grpc:

# batching or filtering
# documentation of default processors: https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor
# community processors: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor
processors:
  batch:

# configure exporters, which forward data to observability backends
# - loki: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md
# - prometheus: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
exporters:
  debug:
    verbosity: detailed
  # logs
  #file/logs:
  #  path: /log/otel/logs.log
  loki:
    endpoint: "${LOKI_ENDPOINT}"
    tls:
      insecure: true
  # metrics
  #file/metrics:
  #  path: /log/otel/metrics.log
  prometheus:
    endpoint: ":8889"
  # traces
  #file/traces:
  #  path: /log/otel/traces.log
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true

# configure extensions to collector and pipelines for metrics, traces and logs
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]